# Schema for the configuration files of the DrupalEasy repositories module.
drupaleasy_repositories.settings:
  type: config_object
  label: 'DrupalEasy repositories settings'
  mapping:
    repositories_plugins:
      type: sequence
      label: 'Repository plugins'
      sequence:
        type: string
